# Generated by Django 5.2.17 on 2026-08-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_enrollment_unique_together_and_more'),
        ('students', '0002_migrate_legacy_enrollments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progress', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='subtopicprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopic_progress', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='students.enrollment'),
        ),
        migrations.AlterField(
            model_name='activityprogress',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to='students.enrollment'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
