# Generated by Django 5.2.17 on 2026-08-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_alter_chapterprogress_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityprogress',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activityprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='case_study_status',
            field=models.CharField(default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='completed_subtopics',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='learning_check_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='learning_check_status',
            field=models.CharField(default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='status',
            field=models.CharField(db_index=True, default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='chapterprogress',
            name='total_subtopics',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='average_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='completed_chapters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='status',
            field=models.CharField(db_index=True, default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='courseprogress',
            name='total_chapters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='completed_activities',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='last_accessed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='status',
            field=models.CharField(db_index=True, default='NOT_STARTED', max_length=20),
        ),
        migrations.AddField(
            model_name='subtopicprogress',
            name='total_required_activities',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
