# Generated by Django 5.2.17 on 2026-08-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_activityprogress_attempt_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'permissions': [('view_all_student_progress', 'Can view all student progress'), ('view_assigned_student_progress', 'Can view assigned student progress')]},
        ),
    ]
