# Generated by Django 5.2.17 on 2026-08-27 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0003_extract_content_media'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('grade', models.CharField(blank=True, max_length=40)),
                ('academic_year', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=20)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_student_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year', 'grade', 'name'],
                'permissions': [('manage_student_groups', 'Can manage student groups')],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='curriculum.course')),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='curriculum.courseversion')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_course_assignments', to=settings.AUTH_USER_MODEL)),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course_assignments', to='students.studentgroup')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'permissions': [('assign_course', 'Can assign courses to students or groups')],
            },
        ),
        migrations.CreateModel(
            name='StudentGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_group_memberships', to=settings.AUTH_USER_MODEL)),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='students.studentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='curriculum.course')),
                ('course_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='curriculum.courseversion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'permissions': [('manage_students', 'Can manage students')],
                'indexes': [models.Index(fields=['student', 'status'], name='enroll_student_status_idx'), models.Index(fields=['course', 'status'], name='enroll_course_status_idx'), models.Index(fields=['course_version', 'status'], name='enroll_version_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'course'), name='unique_active_student_course'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('student', 'course_version'), name='unique_active_student_version')],
            },
        ),
        migrations.CreateModel(
            name='ExternalUserMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('MOODLE', 'Moodle'), ('CANVAS', 'Canvas'), ('MOBILE_APP', 'Mobile app')], max_length=30)),
                ('external_user_id', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'provider'], name='external_user_provider_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_user_id'), name='unique_external_provider_user')],
            },
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['teacher', 'status', 'academic_year'], name='studentgrp_teacher_status_yr'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['student_group', 'status'], name='assignment_group_status_idx'),
        ),
        migrations.AddIndex(
            model_name='courseassignment',
            index=models.Index(fields=['student', 'status'], name='assignment_student_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('student__isnull', True), ('student_group__isnull', False)), models.Q(('student__isnull', False), ('student_group__isnull', True)), _connector='OR'), name='assignment_exactly_one_target'),
        ),
        migrations.AddIndex(
            model_name='studentgroupmember',
            index=models.Index(fields=['student', 'student_group'], name='student_member_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentgroupmember',
            constraint=models.UniqueConstraint(fields=('student_group', 'student'), name='unique_student_group_member'),
        ),
    ]
