# Generated by Django 6.1 on 2026-08-23 13:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Bakery — March actuals', max_length=200)),
                ('price1', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_drop1', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cost1', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price2', models.DecimalField(decimal_places=4, max_digits=12)),
                ('price_drop2', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cost2', models.DecimalField(decimal_places=4, max_digits=12)),
                ('congestion', models.DecimalField(decimal_places=6, max_digits=12)),
                ('fixed_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('current_x', models.IntegerField(default=0)),
                ('current_y', models.IntegerField(default=0)),
                ('product1_label', models.CharField(default='Puffs', max_length=80)),
                ('product2_label', models.CharField(default='Tea', max_length=80)),
                ('unit1', models.CharField(default='puffs per day', max_length=80)),
                ('unit2', models.CharField(default='teas per day', max_length=80)),
                ('currency', models.CharField(default='₹', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_config', to='curriculum.learningactivity')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_models', to='curriculum.learningactivity')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workshop_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
